language: go
sudo: false

go:
- 1.10.x
- 1.11.x
- master

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
- go get golang.org/x/lint/golint
- go get -u github.com/golang/dep/cmd/dep
- make go-dependencies

script:
- make verify

cache:
  directories:
    - vendor