apiVersion: jenkins.io/v1alpha1
kind: Jenkins
metadata:
  name: example
spec:
  master:
    image: corp-jenkins:latest
    readinessProbe:
      httpGet:
        path: /login
        port: 8080
        scheme: HTTP
      failureThreshold: 10
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    livenessProbe:
      httpGet:
        path: /login
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 35
      failureThreshold: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    imagePullPolicy: IfNotPresent
    plugins:
      stashNotifier:1.18:
      - token-macro:2.7
      cloudbees-bitbucket-branch-source:2.4.4:
      - handy-uri-templates-2-api:2.1.6-1.0
      - mercurial:2.0
      simple-theme-plugin:0.5.1: []
  seedJobs:
  - id: sample-seedjob-with-ssh
    credentialType: basicSSHUserPrivateKey
    credentialID: jenkins-k8s-ssh
    targets: "cicd/jobs/*.groovy"
    description: "sample-seedjob-with-ssh repository"
    repositoryBranch: master
    repositoryUrl: git@github.com:tveal/jenkins-k8s.git
  - id: sample-seedjob-with-userpass
    credentialType: usernamePassword
    credentialID: jenkins-k8s-http-user
    targets: "cicd/jobs/*.groovy"
    description: "sample-seedjob-with-userpass repository"
    repositoryBranch: master
    repositoryUrl: https://github.com/tveal/jenkins-k8s.git